name: spacerve
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: 1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_launcher_icons: 0.11.0
  intl: 0.18.0
  very_good_analysis: 4.0.0+1
  dart_extensions: 2.2.2
  image_network: 2.5.1
  onesignal_flutter: 5.0.4
  stack_trace: 1.11.0
  flutter_svg: 2.0.2
  permission_handler: 10.2.0
  go_router: 6.5.2
  gradient_progress_indicator: 1.0.0+5
  freezed_annotation: 2.2.0
  supabase_flutter: 1.6.2
  url_launcher: 6.1.14
  qr_code_scanner: 1.0.1

dev_dependencies:
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  freezed: 2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: pl_PL

# run `flutter pub run flutter_launcher_icons:main` after changing app icon
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
#  adaptive_icon_background: "#000000"
#  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
#  image_path: "assets/images/app_icon_foreground.png"